export const adminResources = {
  sidebarPromos: {
    table: "sidebar_promos",
    label: "Cards da sidebar",
    singular: "card da sidebar",
    description: "Gerencie os cards promocionais exibidos na lateral do blog.",
    orderBy: "sort_order",
    ascending: true,
    titleField: "title",
    subtitleField: "category",
    fields: [
      { name: "category", label: "Categoria", type: "text", required: true },
      { name: "title", label: "Título", type: "text", required: true },
      { name: "image", label: "Imagem", type: "imageUpload", required: true },
      {
        name: "tone",
        label: "Tom visual",
        type: "select",
        required: true,
        options: ["bass", "piano", "guitar"],
      },
      {
        name: "sort_order",
        label: "Ordem de exibição",
        type: "number",
        required: true,
        placeholder: "1",
      },
    ],
  },
  authors: {
    table: "blog_authors",
    label: "Autores",
    singular: "autor",
    description: "Cadastre os autores responsáveis pelos artigos do blog.",
    orderBy: "name",
    ascending: true,
    titleField: "name",
    subtitleField: "instagram_handle",
    fields: [
      { name: "photo", label: "Foto", type: "imageUpload", required: true },
      { name: "name", label: "Nome", type: "text", required: true },
      {
        name: "bio",
        label: "Bio curta",
        type: "textarea",
        required: true,
        placeholder: "Uma breve apresentação do autor.",
      },
      {
        name: "instagram_handle",
        label: "@ do Instagram",
        type: "text",
        required: true,
        placeholder: "@usuario",
      },
      {
        name: "instagram_url",
        label: "Link do Instagram",
        type: "url",
        required: true,
        autoGenerated: true,
      },
    ],
  },
  posts: {
    table: "blog_posts",
    label: "Artigos do blog",
    singular: "artigo",
    description: "Crie, edite e publique conteúdos para o blog.",
    orderBy: "published_at",
    fields: [
      { name: "title", label: "Título", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", required: true, autoGenerated: true },
      { name: "thumbnail", label: "Thumbnail do card", type: "imageUpload" },
      { name: "image", label: "Imagem hero", type: "imageUpload", required: true },
      {
        name: "author_id",
        label: "Autor",
        type: "relationSelect",
        required: true,
        relation: {
          table: "blog_authors",
          valueField: "id",
          labelField: "name",
          orderBy: "name",
        },
      },
      {
        name: "category",
        label: "Categoria",
        type: "select",
        required: true,
        options: [
          "Música",
          "Música II",
          "Música III",
          "Música IV",
          "Música V",
          "Música VI",
          "Música VII",
        ],
      },
      { name: "excerpt", label: "Resumo", type: "textarea", required: true },
      { name: "reading_time", label: "Tempo de leitura", type: "text", required: true },
      { name: "intro", label: "Introdução", type: "textarea", required: true },
      { name: "content", label: "Corpo do artigo", type: "richtext", required: true },
      {
        name: "published_at",
        label: "Publicar em (data e hora)",
        type: "datetime-local",
        required: true,
        help: "Escolha quando o artigo ficará disponível no site. Para publicar imediatamente, informe a data e a hora atuais.",
      },
    ],
  },
};

export function getEmptyRecord(fields) {
  return fields.reduce((record, field) => {
    record[field.name] = "";
    return record;
  }, {});
}
